site_name: Philotechnica

theme:
  name: material
  palette: 
    scheme: slate
    primary: black
    accent: light blue
nav:
  - 'Intro': 'index.md'
  - 'What is Starfall?':
    - 'Overview': 'whatis.md'
    - 'The Map and Exploration': 'whatis/map.md'
    - 'Detection and Display': 'whatis/detect.md'
    - 'Narrative': 'whatis/narrative.md'
  - 'Changelog': 'changelog.md'
  - 'Arke Industries': "https://arkeindustries.com/"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
extra_css:
  - stylesheets/stylesheet.css